#!/usr/bin/env python3
"""Expose the locked CUDA wheels as a toolkit discoverable inside this venv.

Run with .venv/bin/python after uv sync --extra local-llm. FlashInfer and
PyTorch derive CUDA_HOME from the nvcc on PATH; both expect include/ and
lib64/ beside bin/. NVIDIA's wheels live under site-packages instead.
"""

from pathlib import Path
import os
import re
import shlex
import sys
import sysconfig


def link(source: Path, destination: Path) -> None:
    if destination.exists() or destination.is_symlink():
        if destination.resolve() != source.resolve():
            raise RuntimeError(f"Refusing to replace existing path: {destination}")
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.symlink_to(source)


def fix_glibc_math_header(cuda: Path) -> None:
    """Match glibc 2.42+'s rsqrt exception specs in CUDA 13.0's header.

    Newer CUDA headers already include this fix. Keep the change confined to
    the installed venv, and replace the file so uv's hardlinked cache is safe.
    """
    libc = os.confstr("CS_GNU_LIBC_VERSION") or ""
    if not libc.startswith("glibc ") or tuple(map(int, libc.split()[1].split("."))) < (2, 42):
        return
    header = cuda / "include" / "crt" / "math_functions.h"
    original = header.read_text()
    patched, count = re.subn(
        r"(\b(?:rsqrt|rsqrtf)\((?:double|float) [xa]\))(?=;|\))",
        r"\1 noexcept(true)",
        original,
    )
    if not count:
        return
    if count != 4:
        raise RuntimeError(f"Unexpected CUDA math header; found {count} rsqrt declarations")
    temporary = header.with_suffix(".h.oci-tmp")
    temporary.write_text(patched)
    temporary.chmod(header.stat().st_mode & 0o777)
    temporary.replace(header)
    print("Applied CUDA rsqrt header compatibility for glibc 2.42+")


def main() -> None:
    if sys.prefix == sys.base_prefix:
        raise RuntimeError("Run this script with the project's .venv/bin/python")
    venv = Path(sys.prefix)
    cuda = Path(sysconfig.get_path("purelib")) / "nvidia" / "cu13"
    nvcc = cuda / "bin" / "nvcc"
    if not nvcc.is_file():
        raise RuntimeError("CUDA compiler missing; run uv sync --frozen --extra local-llm")
    fix_glibc_math_header(cuda)

    # Keep NVIDIA's complete toolkit layout usable with explicit CUDA_HOME too.
    link(cuda / "lib", cuda / "lib64")
    link(cuda / "lib" / "libcudart.so.13", cuda / "lib" / "libcudart.so")

    # The venv itself is the toolkit root when nvcc is discovered on PATH.
    for header in (cuda / "include").iterdir():
        link(header, venv / "include" / header.name)
    link(cuda / "nvvm", venv / "nvvm")
    for name in ("libcudart.so", "libcudart.so.13", "libcudart_static.a", "libcudadevrt.a"):
        link(cuda / "lib" / name, venv / "lib64" / name)

    # Execute nvcc at its original location so it uses NVIDIA's nvcc.profile
    # and finds its companion binaries, headers, and NVVM compiler correctly.
    wrapper = venv / "bin" / "nvcc"
    marker = "# Generated by OCI scripts/configure_local_cuda.py"
    if wrapper.exists() and marker not in wrapper.read_text():
        raise RuntimeError(f"Refusing to replace existing compiler: {wrapper}")
    wrapper.write_text(f"#!/bin/sh\n{marker}\nexec {shlex.quote(str(nvcc))} \"$@\"\n")
    wrapper.chmod(0o755)
    print(f"Configured CUDA 13.0 toolkit in {venv}; nvcc on the venv PATH uses {nvcc}")


if __name__ == "__main__":
    main()
