# synthetic_data/structured_data.py
"""Parsing and template-based text conversion for structured clinical data events.

Structured events are generated by the LLM as part of the event timeline
(e.g., <encounter>, <lab_result>, <hospitalization>, <pro_assessment>)
and converted to standardized text using deterministic templates.
"""

import logging
import re
from typing import Dict, Any, List, Optional, Tuple

logger = logging.getLogger(__name__)


def _normalize_hyphens(text: str) -> str:
    """Replace common Unicode hyphens/dashes with ASCII hyphen-minus (U+002D).

    LLMs frequently produce non-breaking hyphens (U+2011), en dashes (U+2013),
    and other Unicode dash variants that break regex patterns expecting ASCII hyphens.
    """
    return re.sub(r'[\u2010\u2011\u2012\u2013\u2014\u2015\u2212\uFE58\uFE63\uFF0D]', '-', text)


# ============================================================================
# Constants
# ============================================================================

STRUCTURED_EVENT_TYPES = {"encounter", "lab_result", "hospitalization", "pro_assessment"}

# Lab reference ranges: name -> (unit, low, high)
LAB_REFERENCE_RANGES = {
    # CBC
    "wbc": ("k/uL", 3.7, 10.5),
    "hemoglobin": ("g/dL", 12.0, 16.0),
    "hgb": ("g/dL", 12.0, 16.0),
    "hematocrit": ("%", 35.0, 47.0),
    "hct": ("%", 35.0, 47.0),
    "platelets": ("k/uL", 150, 400),
    "plt": ("k/uL", 150, 400),
    "anc": ("k/uL", 1.5, 8.0),
    "rbc": ("M/uL", 4.2, 5.4),
    # CMP
    "creatinine": ("mg/dL", 0.6, 1.2),
    "cr": ("mg/dL", 0.6, 1.2),
    "bun": ("mg/dL", 7, 20),
    "sodium": ("mEq/L", 136, 145),
    "na": ("mEq/L", 136, 145),
    "potassium": ("mEq/L", 3.5, 5.0),
    "k": ("mEq/L", 3.5, 5.0),
    "chloride": ("mEq/L", 98, 106),
    "cl": ("mEq/L", 98, 106),
    "co2": ("mEq/L", 23, 29),
    "calcium": ("mg/dL", 8.5, 10.5),
    "ca": ("mg/dL", 8.5, 10.5),
    "glucose": ("mg/dL", 70, 100),
    "ast": ("U/L", 10, 40),
    "alt": ("U/L", 7, 56),
    "alp": ("U/L", 44, 147),
    "alkaline phosphatase": ("U/L", 44, 147),
    "bilirubin": ("mg/dL", 0.1, 1.2),
    "total bilirubin": ("mg/dL", 0.1, 1.2),
    "albumin": ("g/dL", 3.5, 5.0),
    "total protein": ("g/dL", 6.0, 8.3),
    # Tumor markers
    "cea": ("ng/mL", 0, 2.5),
    "ca 19-9": ("U/mL", 0, 37),
    "ca 125": ("U/mL", 0, 35),
    "ca 15-3": ("U/mL", 0, 30),
    "afp": ("ng/mL", 0, 15),
    "psa": ("ng/mL", 0, 4.0),
    "ldh": ("U/L", 140, 280),
    # Coagulation
    "inr": ("", 0.8, 1.1),
    "pt": ("seconds", 11, 13.5),
    "ptt": ("seconds", 25, 35),
}

PRO_CTCAE_SEVERITY_LABELS = {
    0: "None",
    1: "Mild",
    2: "Moderate",
    3: "Severe",
    4: "Very Severe",
}

EORTC_SUBSCALE_NAMES = [
    "Physical Functioning",
    "Role Functioning",
    "Emotional Functioning",
    "Cognitive Functioning",
    "Social Functioning",
    "Fatigue",
    "Nausea and Vomiting",
    "Pain",
    "Dyspnea",
    "Insomnia",
    "Appetite Loss",
    "Constipation",
    "Diarrhea",
    "Financial Difficulties",
    "Global Health Status",
]


# ============================================================================
# Parsing functions
# ============================================================================

def parse_encounter_event(event_text: str) -> Dict[str, Any]:
    """Parse an encounter event from the timeline into structured fields.

    Expected format:
        At age 62, outpatient oncology visit. DX: C34.90 (description), Z51.11 (description).
        CPT: 99214 (description), 96413 (description).
    """
    result = {
        "timepoint": "",
        "encounter_type": "",
        "dx_codes": [],  # list of (code, description)
        "cpt_codes": [],  # list of (code, description)
    }

    # Extract timepoint (e.g., "At age 62")
    tp_match = re.match(r'(At age \d+[^,]*),?\s*', event_text, re.IGNORECASE)
    if tp_match:
        result["timepoint"] = tp_match.group(1).strip()
        rest = event_text[tp_match.end():]
    else:
        rest = event_text

    # Extract encounter type (text before DX: or CPT:)
    enc_match = re.match(r'(.*?)(?:\.\s*DX:|DX:|\.\s*CPT:|CPT:|$)', rest, re.IGNORECASE)
    if enc_match:
        result["encounter_type"] = enc_match.group(1).strip().rstrip('.')
        # Truncate qualifying phrases to match structured EHR format
        result["encounter_type"] = re.sub(
            r'\s+(?:for|to|regarding|focusing on|about)\s+.*$',
            '',
            result["encounter_type"],
            flags=re.IGNORECASE,
        )

    # Extract diagnosis codes: pattern like C34.90 (description) or D70.1 (description)
    dx_section_match = re.search(r'DX:\s*(.*?)(?:\.\s*CPT:|CPT:|$)', rest, re.IGNORECASE | re.DOTALL)
    if dx_section_match:
        dx_section = dx_section_match.group(1)
        # Match codes like C34.90, Z51.11, D70.1, etc.
        dx_codes = re.findall(
            r'([A-Z]\d{2}(?:\.\d{1,4})?)\s*\(([^)]+)\)',
            dx_section,
            re.IGNORECASE
        )
        result["dx_codes"] = [(code.upper(), desc.strip()) for code, desc in dx_codes]

    # Extract CPT/HCPCS codes: pattern like 99214 (description)
    cpt_section_match = re.search(r'CPT:\s*(.*?)$', rest, re.IGNORECASE | re.DOTALL)
    if cpt_section_match:
        cpt_section = cpt_section_match.group(1)
        cpt_codes = re.findall(
            r'(\d{5})\s*\(([^)]+)\)',
            cpt_section
        )
        result["cpt_codes"] = [(code, desc.strip()) for code, desc in cpt_codes]

    return result


def parse_hospitalization_event(event_text: str) -> Dict[str, Any]:
    """Parse a hospitalization event from the timeline into structured fields.

    Expected format:
        At age 63, admitted for febrile neutropenia. Principal DX: D70.1
        (Agranulocytosis secondary to cancer chemotherapy). LOS: 4 days.
        Discharge: home.
    """
    result = {
        "timepoint": "",
        "reason": "",
        "principal_dx_code": "",
        "principal_dx_desc": "",
        "los_days": "",
        "discharge_disposition": "",
    }

    # Extract timepoint
    tp_match = re.match(r'(At age \d+[^,]*),?\s*', event_text, re.IGNORECASE)
    if tp_match:
        result["timepoint"] = tp_match.group(1).strip()
        rest = event_text[tp_match.end():]
    else:
        rest = event_text

    # Extract admission reason
    reason_match = re.match(r'admitted (?:for|with|due to)\s+(.*?)(?:\.\s*Principal|Principal|\.\s*DX|DX|$)',
                            rest, re.IGNORECASE)
    if reason_match:
        result["reason"] = reason_match.group(1).strip().rstrip('.')

    # Extract principal diagnosis code
    dx_match = re.search(
        r'(?:Principal\s+)?DX:\s*([A-Z]\d{2}(?:\.\d{1,4})?)\s*\(([^)]+)\)',
        rest,
        re.IGNORECASE
    )
    if dx_match:
        result["principal_dx_code"] = dx_match.group(1).upper()
        result["principal_dx_desc"] = dx_match.group(2).strip()

    # Extract LOS
    los_match = re.search(r'LOS:\s*(\d+)\s*days?', rest, re.IGNORECASE)
    if los_match:
        result["los_days"] = los_match.group(1)

    # Extract discharge disposition
    discharge_match = re.search(r'Discharge:\s*(.+?)(?:\.|$)', rest, re.IGNORECASE)
    if discharge_match:
        result["discharge_disposition"] = discharge_match.group(1).strip()

    return result


def parse_lab_result_event(event_text: str) -> Dict[str, Any]:
    """Parse a lab result event from the timeline into structured fields.

    Expected format:
        At age 62, CBC: WBC 8.2 k/uL (normal), Hgb 11.5 g/dL (low), Plt 245 k/uL (normal).
        CMP: Cr 0.9 mg/dL (normal), AST 28 U/L (normal).
    """
    result = {
        "timepoint": "",
        "panels": [],  # list of {"name": str, "components": [{"name", "value", "unit", "flag"}]}
    }

    # Extract timepoint
    tp_match = re.match(r'(At age \d+[^,]*),?\s*', event_text, re.IGNORECASE)
    if tp_match:
        result["timepoint"] = tp_match.group(1).strip()
        rest = event_text[tp_match.end():]
    else:
        rest = event_text

    # Split into panels by known panel names
    panel_pattern = re.compile(
        r'(CBC|CMP|LFT|BMP|Tumor [Mm]arkers?|Coagulation|Hepatic [Pp]anel|Renal [Pp]anel):\s*',
        re.IGNORECASE
    )

    # Find all panel headers and their positions
    panel_matches = list(panel_pattern.finditer(rest))

    if panel_matches:
        for i, match in enumerate(panel_matches):
            panel_name = match.group(1)
            start = match.end()
            end = panel_matches[i + 1].start() if i + 1 < len(panel_matches) else len(rest)
            panel_text = rest[start:end].strip().rstrip('.')

            components = _parse_lab_components(panel_text)
            result["panels"].append({
                "name": _normalize_panel_name(panel_name),
                "components": components,
            })
    else:
        # No panel headers found - try to parse as a flat list of components
        components = _parse_lab_components(rest)
        if components:
            result["panels"].append({
                "name": "Laboratory Results",
                "components": components,
            })

    return result


def _parse_lab_components(text: str) -> List[Dict[str, str]]:
    """Parse individual lab components from text.

    Matches patterns like:
        WBC 8.2 k/uL (normal)
        Hgb 11.5 g/dL (low)
        Cr 0.9 mg/dL (normal)
        CEA 5.2 ng/mL (high)
    """
    components = []
    # Match: name value unit (flag)
    # Name can be multi-word (e.g., "CA 19-9", "Total Bilirubin", "Alkaline Phosphatase")
    pattern = re.compile(
        r'([A-Za-z][A-Za-z0-9 .\-]*?)\s+'   # name (non-greedy)
        r'([\d.]+)\s*'                        # value
        r'([A-Za-z/%]+(?:/[A-Za-z]+)?)\s*'   # unit
        r'\((\w+)\)',                          # flag in parens
        re.IGNORECASE
    )
    for match in pattern.finditer(text):
        name = match.group(1).strip()
        value = match.group(2)
        unit = match.group(3)
        flag = match.group(4).strip().lower()
        components.append({
            "name": name,
            "value": value,
            "unit": unit,
            "flag": flag,
        })
    return components


def _normalize_panel_name(name: str) -> str:
    """Normalize panel name to display form."""
    mapping = {
        "cbc": "Complete Blood Count (CBC)",
        "cmp": "Comprehensive Metabolic Panel (CMP)",
        "bmp": "Basic Metabolic Panel (BMP)",
        "lft": "Liver Function Tests (LFTs)",
        "hepatic panel": "Hepatic Panel",
        "renal panel": "Renal Panel",
        "coagulation": "Coagulation Panel",
    }
    lower = name.lower().strip()
    if lower in mapping:
        return mapping[lower]
    if lower.startswith("tumor marker"):
        return "Tumor Markers"
    return name


def parse_pro_assessment_event(event_text: str) -> Dict[str, Any]:
    """Parse a PRO assessment event from the timeline into structured fields.

    Expected format:
        At age 63, EORTC QLQ-C30: Physical Function 60, Role Function 40, ...
        PRO-CTCAE: Nausea severity 2, Fatigue severity 3, ...
    """
    result = {
        "timepoint": "",
        "instruments": [],  # list of {"name": str, "scores": [{"subscale", "value"}]}
    }

    # Extract timepoint
    tp_match = re.match(r'(At age \d+[^,]*),?\s*', event_text, re.IGNORECASE)
    if tp_match:
        result["timepoint"] = tp_match.group(1).strip()
        rest = event_text[tp_match.end():]
    else:
        rest = event_text

    # Split by instrument names
    instrument_pattern = re.compile(
        r'(EORTC QLQ-?C30|PRO-?CTCAE|FACT-?G|EQ-?5D-?5L|PROMIS-?29)[^:]*:\s*',
        re.IGNORECASE
    )
    inst_matches = list(instrument_pattern.finditer(rest))

    for i, match in enumerate(inst_matches):
        inst_name = match.group(1).upper().replace(" ", "-")
        start = match.end()
        end = inst_matches[i + 1].start() if i + 1 < len(inst_matches) else len(rest)
        inst_text = rest[start:end].strip().rstrip('.')

        scores = _parse_pro_scores(inst_text, inst_name)
        result["instruments"].append({
            "name": _normalize_instrument_name(inst_name),
            "scores": scores,
        })

    return result


def _parse_pro_scores(text: str, instrument_name: str) -> List[Dict[str, str]]:
    """Parse PRO subscale scores from text."""
    scores = []

    if "CTCAE" in instrument_name.upper():
        # PRO-CTCAE format: "Symptom severity N" or "Symptom N"
        pattern = re.compile(
            r'([A-Za-z][A-Za-z ]+?)\s+'
            r'(?:severity\s+)?(\d)',
            re.IGNORECASE
        )
        for match in pattern.finditer(text):
            subscale = match.group(1).strip()
            value = match.group(2)
            # Skip if the subscale name is just "severity" or similar noise
            if subscale.lower() in ("severity", "frequency", "interference"):
                continue
            scores.append({"subscale": subscale, "value": value})
    else:
        # EORTC QLQ-C30 format: "Subscale Name VALUE" (0-100 scale)
        pattern = re.compile(
            r'([A-Za-z][A-Za-z ]+?)\s+(\d{1,3})(?:\s*[,.]|\s*$|\s+(?=[A-Z]))',
            re.IGNORECASE
        )
        for match in pattern.finditer(text):
            subscale = match.group(1).strip()
            value = match.group(2)
            scores.append({"subscale": subscale, "value": value})

    return scores


def _normalize_instrument_name(name: str) -> str:
    """Normalize PRO instrument name to display form."""
    upper = name.upper().replace(" ", "-")
    if "QLQ" in upper or "C30" in upper:
        return "EORTC QLQ-C30"
    if "CTCAE" in upper:
        return "PRO-CTCAE"
    if "FACT" in upper:
        return "FACT-G"
    if "EQ" in upper and "5D" in upper:
        return "EQ-5D-5L"
    if "PROMIS" in upper:
        return "PROMIS-29"
    return name


# ============================================================================
# Template conversion functions
# ============================================================================

def encounter_to_text(parsed: Dict[str, Any]) -> str:
    """Convert parsed encounter event to standardized text."""
    lines = ["Encounter Record"]

    if parsed.get("timepoint"):
        lines.append(f"  Timepoint: {parsed['timepoint']}")
    if parsed.get("encounter_type"):
        lines.append(f"  Encounter Type: {parsed['encounter_type']}")

    if parsed.get("dx_codes"):
        lines.append("  Diagnosis Codes:")
        for code, desc in parsed["dx_codes"]:
            lines.append(f"    - {code}: {desc}")

    if parsed.get("cpt_codes"):
        lines.append("  Procedure Codes:")
        for code, desc in parsed["cpt_codes"]:
            lines.append(f"    - {code}: {desc}")

    return "\n".join(lines)


def hospitalization_to_text(parsed: Dict[str, Any]) -> str:
    """Convert parsed hospitalization event to standardized text."""
    lines = ["Hospital Admission Record"]

    if parsed.get("timepoint"):
        lines.append(f"  Timepoint: {parsed['timepoint']}")
    if parsed.get("reason"):
        lines.append(f"  Reason for Admission: {parsed['reason']}")
    if parsed.get("principal_dx_code"):
        lines.append(f"  Principal Diagnosis: {parsed['principal_dx_code']} - {parsed.get('principal_dx_desc', '')}")
    if parsed.get("los_days"):
        lines.append(f"  Length of Stay: {parsed['los_days']} days")
    if parsed.get("discharge_disposition"):
        lines.append(f"  Discharge Disposition: {parsed['discharge_disposition']}")

    return "\n".join(lines)


def lab_result_to_text(parsed: Dict[str, Any]) -> str:
    """Convert parsed lab result event to standardized text."""
    lines = ["Laboratory Results"]

    if parsed.get("timepoint"):
        lines.append(f"  Timepoint: {parsed['timepoint']}")

    for panel in parsed.get("panels", []):
        lines.append(f"  {panel['name']}:")
        for comp in panel.get("components", []):
            name = comp["name"]
            value = comp["value"]
            unit = comp.get("unit", "")
            flag = comp.get("flag", "normal")

            # Look up reference range
            ref_range = _get_reference_range(name)
            if ref_range:
                ref_unit, ref_low, ref_high = ref_range
                flag_label = flag.upper() if flag.lower() not in ("normal", "wnl") else "Normal"
                lines.append(
                    f"    {name}: {value} {unit} "
                    f"[Reference: {ref_low}-{ref_high}] - {flag_label}"
                )
            else:
                flag_label = flag.upper() if flag.lower() not in ("normal", "wnl") else "Normal"
                lines.append(f"    {name}: {value} {unit} - {flag_label}")

    return "\n".join(lines)


def _get_reference_range(lab_name: str) -> Optional[Tuple[str, float, float]]:
    """Look up reference range for a lab component by name."""
    lower = lab_name.lower().strip()
    if lower in LAB_REFERENCE_RANGES:
        return LAB_REFERENCE_RANGES[lower]
    # Try common abbreviation mappings
    abbrev_map = {
        "white blood cell": "wbc",
        "white blood cells": "wbc",
        "red blood cells": "rbc",
        "hemoglobin": "hemoglobin",
        "hematocrit": "hematocrit",
        "platelet": "plt",
        "platelets": "plt",
        "absolute neutrophil count": "anc",
        "creatinine": "creatinine",
        "blood urea nitrogen": "bun",
        "alanine aminotransferase": "alt",
        "aspartate aminotransferase": "ast",
    }
    if lower in abbrev_map:
        key = abbrev_map[lower]
        return LAB_REFERENCE_RANGES.get(key)
    return None


def pro_assessment_to_text(parsed: Dict[str, Any]) -> str:
    """Convert parsed PRO assessment event to standardized text."""
    lines = ["Patient-Reported Outcomes Assessment"]

    if parsed.get("timepoint"):
        lines.append(f"  Timepoint: {parsed['timepoint']}")

    for instrument in parsed.get("instruments", []):
        inst_name = instrument["name"]
        lines.append(f"  Instrument: {inst_name}")

        for score in instrument.get("scores", []):
            subscale = score["subscale"]
            value = score["value"]

            if "CTCAE" in inst_name.upper():
                # PRO-CTCAE: 0-4 scale with severity labels
                try:
                    severity_int = int(value)
                    label = PRO_CTCAE_SEVERITY_LABELS.get(severity_int, "")
                    lines.append(f"    {subscale} - Severity: {value}/4 ({label})")
                except ValueError:
                    lines.append(f"    {subscale} - Severity: {value}/4")
            else:
                # EORTC QLQ-C30: 0-100 scale
                lines.append(f"    {subscale}: {value}/100")

    return "\n".join(lines)


# ============================================================================
# Main dispatch function
# ============================================================================

def convert_structured_event_to_text(event_type: str, event_text: str) -> Optional[str]:
    """Convert a structured event to standardized text.

    Args:
        event_type: One of the STRUCTURED_EVENT_TYPES
        event_text: Raw event text from the timeline

    Returns:
        Formatted text string, or None if parsing fails
    """
    try:
        event_text = _normalize_hyphens(event_text)
        if event_type == "encounter":
            parsed = parse_encounter_event(event_text)
            return encounter_to_text(parsed)
        elif event_type == "hospitalization":
            parsed = parse_hospitalization_event(event_text)
            return hospitalization_to_text(parsed)
        elif event_type == "lab_result":
            parsed = parse_lab_result_event(event_text)
            return lab_result_to_text(parsed)
        elif event_type == "pro_assessment":
            parsed = parse_pro_assessment_event(event_text)
            return pro_assessment_to_text(parsed)
        else:
            logger.warning(f"Unknown structured event type: {event_type}")
            return None
    except Exception as e:
        logger.warning(f"Failed to parse structured event ({event_type}): {e}")
        return None
